### ISSUE TITLE
Should setState merge with previous via Object.assign?

### ISSUE THREAD

**Issue by kesne** [vesparny/brcast#1]
First of all, thanks for writing this! It's very useful to have this pattern wrapped up in a node module!

I caught myself expecting `setState()` to merge the new state with the previous state (like React does). Do you think you'd accept a PR to change `currentState = state` to `Object.assign(currentState, state)`?

The downside is that it would rely on people having `Object.assign` polyfilled for older browser support.

**Comment by vesparny** [comment]
Hi @kesne, I'm super glad you find it useful 😀.

I see your point about `setState()`, but the initial idea was to have brcast as a `dumb` store where you can store data in, without any particular logic.

Is there anything preventing you from doing something like that instead?

```js
subscription.setState(Object.assign(subscription.getState(), state))
``` 

Adding the merging strategy built in would probably make `brcast` a little bit too specific (like a small redux without reducers)

Look forward to hear your feedback, and thanks for the suggestion.

**Comment by kesne** [comment]
I think that makes sense! I just ended up wrapping it like in the code sample above without any issues. I'll close this out.

Thanks again!
