### ISSUE TITLE
iterating over subscribers should check to see if id still exists and if it's a function

### ISSUE THREAD

**Issue by brucewpaul** [vesparny/brcast#4]
The 2.0.1 patch release is throwing in error on our site whereas 2.0.0 was fine.

The problem is occurring due to an earlier listener causing a later listener on in the listeners object to no longer exist, thus throwing an error.

Perhaps the iteration over the listeners should check to see if it is a function before calling it?

**Comment by vesparny** [comment]
Can you please provide an example?

**Comment by brucewpaul** [comment]
on the super basic level, if you provide a non function to subscribe, it will throw an error when it is iterating after a setState.

```
TypeError: listeners[id] is not a function
    at Object.keys.forEach.id:10:55
    at Array.forEach
    at Object.setState:10:28
    at eval:36:8
    at eval
```

In our (react) example, we have components that hide/show based on the breakpoint and communicatevia brcast. But if the components are nested, then then the top level component hides it's children, the children functions are no longer present, but brcast still tries to call them, thus throwing an error.

**Comment by brucewpaul** [comment]
i.e. in the subscribe function, we setState on the react component, but the component is no longer mounted

**Comment by brucewpaul** [comment]
`Object.keys(listeners).forEach(id => typeof listeners[id] === 'function' && listeners[id](_state))` fixed it for me

**Comment by vesparny** [comment]
Uhm I see.
The strange thing is that it should have happened also with previous version no?
You think you can paste the code generating the error?
Or meybe a https://codesandbox.io ?

I'm super curious to see the use case.

**Comment by brucewpaul** [comment]
```
this.unsubscribe = this.context[__breakpoint__].subscribe((currentBreakpoint) => {
    this.setState({ currentBreakpoint });
});
```

and in the previous version, it would give a react warning saying that it can't update state on an unmounted component, but this version throws an error

**Comment by brucewpaul** [comment]
there are a lot of pieces to it, but that is the part that is breaking it. And it only breaks in a nested component described above

**Comment by brucewpaul** [comment]
not supplying it a function in the precious version also throws an errors, but the react example is throwing an error now

**Comment by vesparny** [comment]
In which lifecycle method are you setting the subscription?
Are you invoking unsubscribe in componentWillUnmount?

If the key exists, I do not understand how the callback function can be undefined.

**Comment by brucewpaul** [comment]
in `componentDidMount` and yes, it is being unsubscribed in `componentWillUnmount`

**Comment by brucewpaul** [comment]
So with a higher up component, the breakpoint changes and receives the new breakpoint via brcast causing it to unmount. It also had a child that was subscribed to the same brcast, but is not longer there and unsubscribes as it unmounts. It seems at this point, the key is still in the listeners object and errors when it tries to call it

**Comment by vesparny** [comment]
If you unsubscribe then the listener id should be removed from the keys object as well as the callback.
I'd like to write a test for this.

I can certainly add a quick fix as you proposed but I really want to reproduce the error before with and example or a failing unit test.

Are you willing to help with that?

If it's not too complex perhaps you can create a code sandbox?
Or even better a failing test.

Thanks a lot for reporting this

**Comment by brucewpaul** [comment]
my pleasure and ya I'd be down to help out. I doubt I'll be able to get something reproducible up today, but will try tomorrow

**Comment by vesparny** [comment]
Sure no problem. Take your time and thanks again

**Comment by brucewpaul** [comment]
👍

**Comment by vesparny** [comment]
@brucewpaul `2.0.2` has been published.
Thanks for reporting.
